=== RUN   TestIteration1
    iteration1_test.go:50: Не удалось дождаться пока порт 8080 станет доступен для запроса: context deadline exceeded
=== RUN   TestIteration1/TestCounterHandlers
=== RUN   TestIteration1/TestCounterHandlers/update
    iteration1_test.go:150: 
        	Error Trace:	/Users/nikitabar/Dev/metrics_and_alertinc/iteration1_test.go:150
        	            				/Users/nikitabar/Dev/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/counter/testCounter/100": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration1/TestCounterHandlers/update
        	Messages:   	Ошибка при попытке сделать запрос с обновлением counter
    iteration1_test.go:153: 
        	Error Trace:	/Users/nikitabar/Dev/metrics_and_alertinc/iteration1_test.go:153
        	            				/Users/nikitabar/Dev/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 0
        	Test:       	TestIteration1/TestCounterHandlers/update
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/update/counter/testCounter/100'
    iteration1_test.go:158: Оригинальный запрос:
        
        POST /update/counter/testCounter/100 HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== RUN   TestIteration1/TestCounterHandlers/without_id
    iteration1_test.go:166: 
        	Error Trace:	/Users/nikitabar/Dev/metrics_and_alertinc/iteration1_test.go:166
        	            				/Users/nikitabar/Dev/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/counter/": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration1/TestCounterHandlers/without_id
        	Messages:   	Ошибка при попытке сделать запрос с обновлением counter
    iteration1_test.go:169: 
        	Error Trace:	/Users/nikitabar/Dev/metrics_and_alertinc/iteration1_test.go:169
        	            				/Users/nikitabar/Dev/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 404
        	            	actual  : 0
        	Test:       	TestIteration1/TestCounterHandlers/without_id
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/update/counter/'
    iteration1_test.go:174: Оригинальный запрос:
        
        POST /update/counter/ HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== RUN   TestIteration1/TestCounterHandlers/invalid_value
    iteration1_test.go:182: 
        	Error Trace:	/Users/nikitabar/Dev/metrics_and_alertinc/iteration1_test.go:182
        	            				/Users/nikitabar/Dev/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/counter/testCounter/none": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration1/TestCounterHandlers/invalid_value
        	Messages:   	Ошибка при попытке сделать запрос с обновлением counter
    iteration1_test.go:185: 
        	Error Trace:	/Users/nikitabar/Dev/metrics_and_alertinc/iteration1_test.go:185
        	            				/Users/nikitabar/Dev/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 400
        	            	actual  : 0
        	Test:       	TestIteration1/TestCounterHandlers/invalid_value
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/update/counter/testCounter/none'
    iteration1_test.go:190: Оригинальный запрос:
        
        POST /update/counter/testCounter/none HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== RUN   TestIteration1/TestGaugeHandlers
=== RUN   TestIteration1/TestGaugeHandlers/update
    iteration1_test.go:98: 
        	Error Trace:	/Users/nikitabar/Dev/metrics_and_alertinc/iteration1_test.go:98
        	            				/Users/nikitabar/Dev/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/gauge/testGauge/100": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration1/TestGaugeHandlers/update
        	Messages:   	Ошибка при попытке сделать запрос с обновлением gauge
    iteration1_test.go:101: 
        	Error Trace:	/Users/nikitabar/Dev/metrics_and_alertinc/iteration1_test.go:101
        	            				/Users/nikitabar/Dev/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 0
        	Test:       	TestIteration1/TestGaugeHandlers/update
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/update/gauge/testGauge/100'
    iteration1_test.go:106: Оригинальный запрос:
        
        POST /update/gauge/testGauge/100 HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== RUN   TestIteration1/TestGaugeHandlers/without_id
    iteration1_test.go:114: 
        	Error Trace:	/Users/nikitabar/Dev/metrics_and_alertinc/iteration1_test.go:114
        	            				/Users/nikitabar/Dev/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/gauge/": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration1/TestGaugeHandlers/without_id
        	Messages:   	Ошибка при попытке сделать запрос с обновлением gauge
    iteration1_test.go:117: 
        	Error Trace:	/Users/nikitabar/Dev/metrics_and_alertinc/iteration1_test.go:117
        	            				/Users/nikitabar/Dev/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 404
        	            	actual  : 0
        	Test:       	TestIteration1/TestGaugeHandlers/without_id
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/update/gauge/'
    iteration1_test.go:122: Оригинальный запрос:
        
        POST /update/gauge/ HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== RUN   TestIteration1/TestGaugeHandlers/invalid_value
    iteration1_test.go:130: 
        	Error Trace:	/Users/nikitabar/Dev/metrics_and_alertinc/iteration1_test.go:130
        	            				/Users/nikitabar/Dev/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/gauge/testGauge/none": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration1/TestGaugeHandlers/invalid_value
        	Messages:   	Ошибка при попытке сделать запрос с обновлением gauge
    iteration1_test.go:133: 
        	Error Trace:	/Users/nikitabar/Dev/metrics_and_alertinc/iteration1_test.go:133
        	            				/Users/nikitabar/Dev/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 400
        	            	actual  : 0
        	Test:       	TestIteration1/TestGaugeHandlers/invalid_value
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/update/gauge/testGauge/none'
    iteration1_test.go:138: Оригинальный запрос:
        
        POST /update/gauge/testGauge/none HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== RUN   TestIteration1/TestUnknownHandlers
=== RUN   TestIteration1/TestUnknownHandlers/update_invalid_type
    iteration1_test.go:202: 
        	Error Trace:	/Users/nikitabar/Dev/metrics_and_alertinc/iteration1_test.go:202
        	            				/Users/nikitabar/Dev/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/unknown/testCounter/100": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration1/TestUnknownHandlers/update_invalid_type
        	Messages:   	Ошибка при попытке сделать запрос с не корректным типом метрики
    iteration1_test.go:205: 
        	Error Trace:	/Users/nikitabar/Dev/metrics_and_alertinc/iteration1_test.go:205
        	            				/Users/nikitabar/Dev/metrics_and_alertinc/suite.go:91
        	Error:      	[]int{400, 501} does not contain 0
        	Test:       	TestIteration1/TestUnknownHandlers/update_invalid_type
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/update/unknown/testCounter/100'
    iteration1_test.go:210: Оригинальный запрос:
        
        POST /update/unknown/testCounter/100 HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== RUN   TestIteration1/TestUnknownHandlers/update_invalid_method
    iteration1_test.go:218: 
        	Error Trace:	/Users/nikitabar/Dev/metrics_and_alertinc/iteration1_test.go:218
        	            				/Users/nikitabar/Dev/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/updater/counter/testCounter/100": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration1/TestUnknownHandlers/update_invalid_method
        	Messages:   	Ошибка при попытке сделать запрос с не корректным типом метрики
    iteration1_test.go:221: 
        	Error Trace:	/Users/nikitabar/Dev/metrics_and_alertinc/iteration1_test.go:221
        	            				/Users/nikitabar/Dev/metrics_and_alertinc/suite.go:91
        	Error:      	[]int{400, 404} does not contain 0
        	Test:       	TestIteration1/TestUnknownHandlers/update_invalid_method
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/updater/counter/testCounter/100'
    iteration1_test.go:226: Оригинальный запрос:
        
        POST /updater/counter/testCounter/100 HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== NAME  TestIteration1
    iteration1_test.go:70: Процесс завершился с не нулевым статусом 2
    iteration1_test.go:82: Получен STDOUT лог процесса:
        
        server: main: restorer: read file error: empty fail
        panic: repository: database: CheckConn: failed to connect to `host=/private/tmp user=nikitabar database=`: dial error (dial unix /private/tmp/.s.PGSQL.5432: connect: no such file or directory)
        
        goroutine 1 [running]:
        main.main()
        	/Users/nikitabar/Dev/metrics_and_alertinc/cmd/server/main.go:53 +0x7b0
--- FAIL: TestIteration1 (20.02s)
    --- FAIL: TestIteration1/TestCounterHandlers (0.01s)
        --- FAIL: TestIteration1/TestCounterHandlers/update (0.01s)
        --- FAIL: TestIteration1/TestCounterHandlers/without_id (0.00s)
        --- FAIL: TestIteration1/TestCounterHandlers/invalid_value (0.00s)
    --- FAIL: TestIteration1/TestGaugeHandlers (0.00s)
        --- FAIL: TestIteration1/TestGaugeHandlers/update (0.00s)
        --- FAIL: TestIteration1/TestGaugeHandlers/without_id (0.00s)
        --- FAIL: TestIteration1/TestGaugeHandlers/invalid_value (0.00s)
    --- FAIL: TestIteration1/TestUnknownHandlers (0.00s)
        --- FAIL: TestIteration1/TestUnknownHandlers/update_invalid_type (0.00s)
        --- FAIL: TestIteration1/TestUnknownHandlers/update_invalid_method (0.00s)
=== RUN   TestIteration2A
=== RUN   TestIteration2A/TestAgent
=== RUN   TestIteration2A/TestAgent/receive_data_from_agent
=== NAME  TestIteration2A
    iteration2a_test.go:80: Получен STDOUT лог процесса:
        
        useCase: sender: sendPost: do request: Post "http://localhost:8080/update/gauge/Lookups/0.00": EOF
        interrupt
--- PASS: TestIteration2A (10.04s)
    --- PASS: TestIteration2A/TestAgent (0.00s)
        --- PASS: TestIteration2A/TestAgent/receive_data_from_agent (0.00s)
=== RUN   TestIteration2B
=== RUN   TestIteration2B/TestFilesPresence
=== RUN   TestIteration2B/TestServerCoverage
    iteration2b_test.go:87: 
        	Error Trace:	/Users/nikitabar/Dev/metrics_and_alertinc/iteration2b_test.go:87
        	Error:      	Received unexpected error:
        	            	exit status 1
        	Test:       	TestIteration2B/TestServerCoverage
        	Messages:   	Невозможно получить результат выполнения команды: /usr/local/go/bin/go test -cover ./.... Вывод:
        	            	
        	            	 ?   	github.com/NikitaBarysh/metrics_and_alertinc/cmd/agent	[no test files]
        	            	?   	github.com/NikitaBarysh/metrics_and_alertinc/cmd/server	[no test files]
        	            	?   	github.com/NikitaBarysh/metrics_and_alertinc/internal/entity	[no test files]
        	            	?   	github.com/NikitaBarysh/metrics_and_alertinc/internal/interface/compress	[no test files]
        	            	?   	github.com/NikitaBarysh/metrics_and_alertinc/internal/interface/config/agent	[no test files]
        	            	?   	github.com/NikitaBarysh/metrics_and_alertinc/internal/interface/config/server	[no test files]
        	            	?   	github.com/NikitaBarysh/metrics_and_alertinc/internal/interface/logger	[no test files]
        	            	?   	github.com/NikitaBarysh/metrics_and_alertinc/internal/interface/models	[no test files]
        	            	?   	github.com/NikitaBarysh/metrics_and_alertinc/internal/interface/repository	[no test files]
        	            	?   	github.com/NikitaBarysh/metrics_and_alertinc/internal/interface/repository/postgres	[no test files]
        	            	?   	github.com/NikitaBarysh/metrics_and_alertinc/internal/router	[no test files]
        	            	handler_test: safe: init db: repository: database: CheckConn: failed to connect to `host=/private/tmp user=nikitabar database=`: dial error (dial unix /private/tmp/.s.PGSQL.5432: connect: no such file or directory)
        	            	/var/folders/84/lzqlk4f168v1_zvxb2jmrx280000gn/T/go-build627398954/b216/handlers.test flag redefined: a
        	            	--- FAIL: TestHandler_Safe (0.00s)
        	            	    --- FAIL: TestHandler_Safe/Test#2,_check_if_all_correct (0.00s)
        	            	panic: /var/folders/84/lzqlk4f168v1_zvxb2jmrx280000gn/T/go-build627398954/b216/handlers.test flag redefined: a [recovered]
        	            		panic: /var/folders/84/lzqlk4f168v1_zvxb2jmrx280000gn/T/go-build627398954/b216/handlers.test flag redefined: a
        	            	
        	            	goroutine 37 [running]:
        	            	testing.tRunner.func1.2({0x104befea0, 0x1400010bc20})
        	            		/usr/local/go/src/testing/testing.go:1526 +0x1c8
        	            	testing.tRunner.func1()
        	            		/usr/local/go/src/testing/testing.go:1529 +0x384
        	            	panic({0x104befea0, 0x1400010bc20})
        	            		/usr/local/go/src/runtime/panic.go:884 +0x204
        	            	flag.(*FlagSet).Var(0x1400012a120, {0x104c91d70, 0x1400012a780}, {0x104bb4c68, 0x1}, {0x104b30aa6, 0x1e})
        	            		/usr/local/go/src/flag/flag.go:982 +0x2a4
        	            	flag.StringVar(...)
        	            		/usr/local/go/src/flag/flag.go:853
        	            	github.com/NikitaBarysh/metrics_and_alertinc/internal/interface/config/server.ParseServerConfig()
        	            		/Users/nikitabar/Dev/metrics_and_alertinc/internal/interface/config/server/config.go:53 +0x80
        	            	github.com/NikitaBarysh/metrics_and_alertinc/internal/handlers.TestHandler_Safe.func1(0x0?)
        	            		/Users/nikitabar/Dev/metrics_and_alertinc/internal/handlers/handlers_test.go:62 +0x350
        	            	testing.tRunner(0x14000210000, 0x1400010bb80)
        	            		/usr/local/go/src/testing/testing.go:1576 +0x10c
        	            	created by testing.(*T).Run
        	            		/usr/local/go/src/testing/testing.go:1629 +0x368
        	            	FAIL	github.com/NikitaBarysh/metrics_and_alertinc/internal/handlers	0.012s
        	            	?   	github.com/NikitaBarysh/metrics_and_alertinc/internal/storage	[no test files]
        	            	?   	github.com/NikitaBarysh/metrics_and_alertinc/internal/useCase/flusher	[no test files]
        	            	?   	github.com/NikitaBarysh/metrics_and_alertinc/internal/useCase/sender	[no test files]
        	            	ok  	github.com/NikitaBarysh/metrics_and_alertinc/internal/service	(cached)	coverage: 2.4% of statements
        	            	FAIL
--- FAIL: TestIteration2B (1.05s)
    --- PASS: TestIteration2B/TestFilesPresence (0.00s)
    --- FAIL: TestIteration2B/TestServerCoverage (1.05s)
=== RUN   TestIteration3A
=== RUN   TestIteration3A/TestFrameworkUsage
--- PASS: TestIteration3A (0.00s)
    --- PASS: TestIteration3A/TestFrameworkUsage (0.00s)
=== RUN   TestIteration3B
